name: "Music Website"
description: "A Website for a Musician"

# url: "http://127.0.0.1:4000/"
 url: "http://kalenenc.github.io/music-website/"

#paginate: 10

markdown: kramdown
permalink: pretty
# highlighter: pygments
